### PR TITLE
Fixed #62

### LINKED ISSUE #62: UICollectionViewFlowLayout cache mismatched frame (iOS9, xCode7)
AKPickerView outputs this when running on iOS9, xCode7:

Logging only once for UICollectionViewFlowLayout cache mismatched frame
UICollectionViewFlowLayout has cached frame mismatch for index path <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0} - cached value: {{170.66667847961008, 0}, {72.999976338098122, 736}}; expected value: {{170.66666666666666, 0}, {73, 736}}
This is likely occurring because the flow layout subclass AKCollectionViewLayout is modifying attributes returned by UICollectionViewFlowLayout without copying them

### PR DESCRIPTION
**Pull request by mladen-stankovic**
I've fixed bug described in issue #62, can you please accept this pull request and update podspec file?

### CODE REVIEW

**Comment by Akkyie** [comment]
Merged. Thank you for your contribution and I'm sorry for my late response!

**Comment by mladen-stankovic** [comment]
No problem, I'm happy to contribute :)
Seems like tag 0.2.7 is on the same commit as tag 0.2.6.

Can you move tag 0.2.7 to the latest commit?

Thank you for this great horizontal picker!

**Comment by akkyie** [comment]
I fixed the wrong tag.
It's my pleasure, thank you for using AKPickerView!

**Comment by mladen-stankovic** [comment]
Hi, there are 3 commits to master since 0.2.7 tag (tags 0.2.6 and 0.2.7 are the same).
Can you please fix this?

Thanks

**Comment by mladen-stankovic** [comment]
Can you also commit podspec.json to the CocoaPods Specs?
https://github.com/CocoaPods/Specs/tree/master/Specs/AKPickerView

**Comment by mladen-stankovic** [comment]
Hi, any chance of fixing 0.2.7 tag and updating CocoaPods Specs (see my 2 previous posts) ?

Thank you

**Comment by akkyie** [comment]
Done. Thanks https://raw.githubusercontent.com/CocoaPods/Specs/5b3d72e3ac73f2e97343bd7b09ec8d5c6ee31f4d/Specs/AKPickerView/0.2.7/AKPickerView.podspec.json

**Comment by mladen-stankovic** [comment]
Thank you for your quick response.

Sorry for bothering you but tag 0.2.7 is not correct.

https://github.com/Akkyie/AKPickerView/releases/tag/0.2.7

There it says
Akkyie tagged this on May 14 · 3 commits to master since this tag

**Comment by akkyie** [comment]
Sorry for my repeatedly mistake… I fixed it.

**Comment by mladen-stankovic** [comment]
No worries, thank you for the fixes!
Greetings to Japan :)

**Pull request merged**
