### PR TITLE
Added property for disabling fisheye style including mask

### PR DESCRIPTION
**Pull request by kafejo**

### CODE REVIEW

**Comment by Akkyie** [comment]
Well, how does it differ from using `AKPickerViewStyleFlat`?

**Comment by kafejo** [comment]
AKPickerViewStyleFlat didn't work for me, there was always mask.

**Comment by Akkyie** [comment]
I got it, indeed you should be able to disable the mask, but I think there's no relation between the masking and fisheyeFactor. It can be disabled simply by `pickerView.fisheyeFactor = 0.0;`. Do you have any reasons?

**Comment by kafejo** [comment]
Well simple pickerView.fisheyeFactor = 0.0 doesn't work for me. No idea y.

**Comment by Akkyie** [comment]
Added `maskDisabled` property, I'm still not sure if it is what you mean however (ffc7a820a958af00bb0cf1abf80354dfd0a5d082 .)
Actually, there was a possibility that changing `fisheyeFactor` after initialization was not reflected. I also fixed this, so it might solve your problem, perhaps.

**Comment by kafejo** [comment]
Ok then, in that case this pull is useless.

**Comment by Akkyie** [comment]
Anyway thank you for your cooperation.

**Pull request closed without merging**
